### ISSUE TITLE
KEY

### ISSUE THREAD

**Issue by agraciabona** [TIGAL/OpenTracker#4]
Since release december 18 I get an error related to the KEY used to connect to the server.
It seems KEY defined in tracker.h (#define KEY "VnrZd391cH") is not valid, I have to define instead KEY ".\b"

**Comment by agraciabona** [comment]
Hi,
Don't know why but my password in http://opentracker.tigal.com is ".\b", I mean two characters: a dot followed by a backspace...
The problem is I can't change it...  can you put in my account a writable password please?
Thanks

**Comment by opensourcegps** [comment]
please email support@opengps.net from your account email address and I'll reset your password.
